### ISSUE TITLE
Support to read mail-config properties from helm values.yaml

### ISSUE THREAD

**Issue by shkmaaz11** [camunda-community-hub/camunda-platform-7-mail#22]
Support to read mail-config properties from helm values.yaml

**Comment by asoltesz** [comment]
The mail connector cannot directly support Helm values files since it cannot assume the deployment environment is Kubernetes.

This is why it is configured via the MAIL_CONFIG environment variable and a properties file.

However, supporting Helm deployment is easily done by following:

1) Accept the mail configuration in your Values.yaml, like this:
 
~~~
...
mail:
    smtp:
        auth: true
        port: 465
...
~~~

2) Render the mail.properties file with a Helm template

~~~
mail.smtp.auth={{ .Values.mail.smtp.auth }}
mail.smtp.port={{ .Values.mail.smtp.port }}
~~~

3) Put the mail.properties file in a ConfigMap and mount it in your deployment on /config/mail.properties (or anywhere else you prefer) 

4) Set the MAIL_CONFIG environment variable to "file:/config/mail.properties" in your deployment
